@BASE_URL= http://localhost:8080/api/v1
@OPENING_ID= 2

### Get all openings
GET {{BASE_URL}}/openings

### Create a new opening
POST {{BASE_URL}}/opening
Content-Type: application/json

{
	"role": "Senior Go Engineer",
	"company": "UltraSoft",
	"location": "New York",
	"remote": true,	
	"link": "vaga.com/vagapica",
	"salary": 520000
}

### Get a specific opening by ID
GET {{BASE_URL}}/opening?id={{OPENING_ID}}

### Update an existing opening by ID
PUT {{BASE_URL}}/opening?id={{OPENING_ID}}
Content-Type: application/json

{
	"role": "Senior Next.js Engineer",
	"company": "Gaagle",
	"location": "New York",
	"remote": true,	
	"link": "vaga.com/vagapica",
	"salary": 520000
}

### Delete an opening by ID
DELETE {{BASE_URL}}/opening?id={{OPENING_ID}}